# Стейдж для сборки
FROM node:22-alpine as build

# Установка рабочей директории
WORKDIR /app

# Копируем файлы package.json и package-lock.json (если есть) для установки зависимостей
COPY package*.json ./ 

# Устанавливаем зависимости
RUN npm install 

# Копируем остальные файлы проекта
COPY . .

# Выполняем сборку фронтенда
RUN npm run build 

# Стейдж для деплоя через nginx
FROM nginx:stable-alpine

# Копируем собранные файлы из предыдущего стейджа в директорию Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфигурацию Nginx
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf

# Открываем порт 5173 для Nginx
EXPOSE 5173

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]
